// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0JYSGcThUH3B78O5daf8GMDa_K3a9xcw',
    appId: '1:603631209902:web:28ea6fe384feba20e30c3f',
    messagingSenderId: '603631209902',
    projectId: 'unihub-db7fa',
    authDomain: 'unihub-db7fa.firebaseapp.com',
    storageBucket: 'unihub-db7fa.firebasestorage.app',
    measurementId: 'G-LKZNQKQE7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJapsBqkgXJb38hhwII0S7rOYQaxJH9wI',
    appId: '1:603631209902:android:32156bd3e5062186e30c3f',
    messagingSenderId: '603631209902',
    projectId: 'unihub-db7fa',
    storageBucket: 'unihub-db7fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXWJvUkQ4QuSUkndRY3gjo2tddhLSJ0-A',
    appId: '1:603631209902:ios:d4be4a6625704847e30c3f',
    messagingSenderId: '603631209902',
    projectId: 'unihub-db7fa',
    storageBucket: 'unihub-db7fa.firebasestorage.app',
    iosClientId: '603631209902-8529c9a4ptss5a5v23v8cosis650hrce.apps.googleusercontent.com',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXWJvUkQ4QuSUkndRY3gjo2tddhLSJ0-A',
    appId: '1:603631209902:ios:d4be4a6625704847e30c3f',
    messagingSenderId: '603631209902',
    projectId: 'unihub-db7fa',
    storageBucket: 'unihub-db7fa.firebasestorage.app',
    iosClientId: '603631209902-8529c9a4ptss5a5v23v8cosis650hrce.apps.googleusercontent.com',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0JYSGcThUH3B78O5daf8GMDa_K3a9xcw',
    appId: '1:603631209902:web:795478c0c8dcb108e30c3f',
    messagingSenderId: '603631209902',
    projectId: 'unihub-db7fa',
    authDomain: 'unihub-db7fa.firebaseapp.com',
    storageBucket: 'unihub-db7fa.firebasestorage.app',
    measurementId: 'G-6HT5HGPFM8',
  );
}
